#!/bin/sh

while true; do
    energy_now=$(cat /sys/class/power_supply/BAT0/energy_now)
    energy_full=$(cat /sys/class/power_supply/BAT0/energy_full)
    battery=$(echo "scale=0; ($energy_now*100)/$energy_full" | bc)
    essid=$(iwconfig 2>&1 | grep ESSID | sed -e 's@.*ESSID:\(.\+\).*@\1@g' -e 's@"@@g' -e 's@[ ]\+$@@g')
    echo "T${battery}% | ${essid} | $(date)" # > $PANEL_FIFO
    sleep 1
done
