#! /bin/sh

source $(dirname $0)/config

while read -r line ; do
    case $line in
        S*)
            sys_infos="%{r}%{F#ffee9a00}${line#?}%{F-}"
            ;;
        T*)
            date_info="%{r}%{F#ffee9a00}${line#?}%{F-}"
            ;;
        W*)
            wm_infos="%{l}"
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [OFU]*)
                        # active desktop
                        wm_infos="$wm_infos%{F#FF859900}%{R} $name %{R}%{F-}"
                        ;;
                    o*)
                        # inactive but occupied desktop
                        wm_infos="$wm_infos%{F$COLOR_OCCUPIED} $name %{F-}"
                        ;;
                    f*)
                        # inactive desktop
                        #wm_infos="$wm_infos%{F$COLOR_INACTIVE} $name %{F-}"
                        wm_infos="$wm_infos $name "
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos%{U$COLOR_URGENT}%{+u} $name %{-u}"
                        ;;
                    L*)
                        # layout
#                        layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
                        wm_infos="$wm_infos $layout"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "$wm_infos$date_info"
done
